from collections.abc import Sequence

from capture_api.world.rng import Stream

MAIL_DOMAIN = "quillmere.example"

FIRST_NAMES: tuple[str, ...] = (
    "Adia",
    "Alka",
    "Amara",
    "Amel",
    "Anouk",
    "Arben",
    "Aroha",
    "Beren",
    "Bodil",
    "Bram",
    "Brielle",
    "Calix",
    "Cato",
    "Cerys",
    "Csilla",
    "Dagny",
    "Dario",
    "Delphine",
    "Dimi",
    "Dinah",
    "Eero",
    "Eline",
    "Elif",
    "Emeka",
    "Enno",
    "Esben",
    "Fabiola",
    "Faruk",
    "Fenna",
    "Filipa",
    "Fintan",
    "Freja",
    "Gael",
    "Gita",
    "Greta",
    "Gunnar",
    "Hana",
    "Hedda",
    "Henrike",
    "Hilde",
    "Ilir",
    "Ilka",
    "Imani",
    "Ines",
    "Ingvar",
    "Iris",
    "Ivo",
    "Janne",
    "Jarek",
    "Jasna",
    "Joris",
    "Juno",
    "Kaia",
    "Kamil",
    "Kenji",
    "Kiran",
    "Lauri",
    "Leander",
    "Lieke",
    "Linnea",
    "Lior",
    "Lorcan",
    "Lucia",
    "Maarten",
    "Maia",
    "Malou",
    "Manu",
    "Marek",
    "Mariana",
    "Mattis",
    "Mila",
    "Mirek",
    "Nadia",
    "Nalu",
    "Neela",
    "Nils",
    "Noor",
    "Nuno",
    "Odile",
    "Oksana",
    "Orla",
    "Osian",
    "Ottilie",
    "Paavo",
    "Panos",
    "Petra",
    "Pia",
    "Quentin",
    "Rafa",
    "Ragna",
    "Rania",
    "Rasmus",
    "Reija",
    "Remy",
    "Rhian",
    "Rina",
    "Roos",
    "Rune",
    "Saara",
    "Sacha",
    "Salma",
    "Sanne",
    "Savvas",
    "Selma",
    "Senna",
    "Sepp",
    "Shirin",
    "Sigrun",
    "Siri",
    "Solveig",
    "Soren",
    "Stig",
    "Suvi",
    "Taavi",
    "Tamar",
    "Tariq",
    "Tessa",
    "Thijs",
    "Tomas",
    "Toril",
    "Ugo",
    "Ulla",
    "Vala",
    "Veit",
    "Vera",
    "Vidar",
    "Wiebke",
    "Xenia",
    "Yara",
    "Yusra",
    "Zaid",
    "Zara",
    "Zeno",
    "Zofia",
)
"""~130 invented first names."""

LAST_NAMES: tuple[str, ...] = (
    "Aldenhoff",
    "Ashgrove",
    "Barenthal",
    "Bellmark",
    "Bexhill",
    "Braemore",
    "Caldenhoe",
    "Carrow",
    "Cedrin",
    "Dalmoor",
    "Darnholt",
    "Deverell",
    "Draska",
    "Elvindal",
    "Embersby",
    "Fairholt",
    "Fennmark",
    "Fontaro",
    "Gallowmere",
    "Garnholm",
    "Gravendal",
    "Halvorsk",
    "Harrowby",
    "Hesselmark",
    "Ibarrola",
    "Illerton",
    "Janovec",
    "Jarnholt",
    "Kaldbek",
    "Kessendorf",
    "Kirvala",
    "Lachmond",
    "Landvik",
    "Larrimore",
    "Lindqvarn",
    "Marnhold",
    "Melbroke",
    "Merivale",
    "Narvenko",
    "Nessholm",
    "Northbury",
    "Olverra",
    "Ostervik",
    "Pallenberg",
    "Penhallow",
    "Petrescan",
    "Quillfeather",
    "Ravensmoor",
    "Redwaith",
    "Rothvale",
    "Salvatierre",
    "Sandrup",
    "Sarkissen",
    "Selbourne",
    "Skarnvik",
    "Sondergard",
    "Stavrelli",
    "Tannenholm",
    "Thorburne",
    "Tillingsworth",
    "Torvald",
    "Ulvestad",
    "Vallenbrook",
    "Varga",
    "Vendral",
    "Vessholt",
    "Wachtel",
    "Weyburn",
    "Whitlock",
    "Ximenes",
    "Yarrowby",
    "Zeldovic",
    "Zumthorpe",
    "Abernathe",
    "Bracklow",
    "Cindermere",
    "Dunhollow",
    "Erskvall",
    "Farrowdale",
    "Glaskin",
    "Hollenbeck",
    "Inverwood",
    "Jessamin",
    "Kalvedis",
    "Lomarque",
    "Mistbourne",
    "Noorvik",
    "Oakhaven",
    "Prydwen",
    "Quarrenden",
    "Rimsholt",
    "Strandfeld",
    "Thalmoor",
    "Underhays",
    "Vaughanly",
    "Wrenfield",
    "Yvestad",
    "Zarnowitz",
    "Ambervale",
    "Belcastro",
    "Corvenhall",
    "Drenholm",
    "Eastmarch",
    "Falkenrath",
    "Greymouth",
    "Havelund",
    "Iskandari",
    "Jorbeck",
    "Kendrall",
    "Lundwick",
    "Morrowgate",
    "Nyquistan",
    "Orlenska",
    "Pelgrave",
    "Rundqvist",
    "Sableton",
    "Tarrowen",
    "Veldhuis",
    "Westerby",
    "Yolanthe",
)
"""~120 invented family names."""


def login(first: str, last: str) -> str:
    return f"{first.lower()}.{last.lower()}"


def mailbox(user: str) -> str:
    return f"{user}@{MAIL_DOMAIN}"


def assign_users(seed: str, count: int) -> tuple[str, ...]:
    pool_size = len(FIRST_NAMES) * len(LAST_NAMES)
    if not 0 <= count <= pool_size:
        raise ValueError(f"cannot draw {count} distinct users from {pool_size} combinations")
    stream = Stream(seed, "users")
    picked = stream.sample(range(pool_size), count)
    return tuple(
        login(FIRST_NAMES[index // len(LAST_NAMES)], LAST_NAMES[index % len(LAST_NAMES)])
        for index in picked
    )


def display_name(user: str) -> str:
    return " ".join(part.capitalize() for part in user.split("."))


def name_pool() -> Sequence[str]:
    return (*FIRST_NAMES, *LAST_NAMES)
