import asyncio
import hashlib
import html
import json
import re
import zipfile
from collections.abc import Callable, Iterator
from contextlib import asynccontextmanager, suppress
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from io import BytesIO
from typing import Annotated, Any, cast

from fastapi import Depends, FastAPI
from starlette.requests import HTTPConnection

from capture_api.domain.base import iso_ms
from capture_api.domain.models import Case, Export, ExportState
from capture_api.errors import DomainError
from capture_api.workspace.cases import CaseStore
from capture_api.world.clock import CaptureClock, TimeSource
from capture_api.world.files import ascii_fallback_name
from capture_api.world.ids import parse_session_id
from capture_api.world.types import World

QUEUED_S = 0.3
"""Seconds the job stays ``queued`` before it starts running."""
DURATION_S = 2.5
"""Seconds from creation to ``ready``."""
TTL_S = 900.0
"""A ready export is downloadable for 15 minutes."""
CHUNK = 64 * 1024

ZIP_MEDIA_TYPE = "application/zip"


@dataclass(slots=True)
class ExportRecord:
    id: str
    case_id: str
    created_mono: float
    filename: str
    state: ExportState = "queued"
    ready_mono: float | None = None
    ready_at: datetime | None = None
    archive: bytes | None = field(default=None, repr=False)

    @property
    def sizeof(self) -> int:
        return len(self.archive or b"")


def archive_filename(case: Case) -> str:
    slug = re.sub(r"\s+", "-", case.title.strip()) or "case"
    return f"capture_api-{case.id}-{slug}.zip"


def _evidence_document(world: World | None, case: Case, generated_at: datetime) -> dict[str, Any]:
    entries: list[dict[str, Any]] = []
    for pin in case.evidence:
        entry: dict[str, Any] = {
            "session_id": pin.session_id,
            "pinned_by": pin.pinned_by,
            "pinned_at": iso_ms(pin.pinned_at),
        }
        if pin.stage is not None:
            entry["stage"] = pin.stage
        if pin.note is not None:
            entry["note"] = pin.note
        row = _row(world, pin.session_id)
        if row is not None and world is not None:
            entry["session"] = world.to_session_row(row).model_dump(mode="json")
        entries.append(entry)
    return {
        "generated_at": iso_ms(generated_at),
        "case": {
            "id": case.id,
            "title": case.title,
            "status": case.status,
            "severity": case.severity,
            "owner_id": case.owner_id,
            "summary": case.summary,
            "version": case.version,
            "created_at": iso_ms(case.created_at),
            "updated_at": iso_ms(case.updated_at),
        },
        "evidence": entries,
        "notes": [
            {
                "id": note.id,
                "author_id": note.author_id,
                "body": note.body,
                "created_at": iso_ms(note.created_at),
            }
            for note in case.notes
        ],
    }


def _row(world: World | None, session_id: str) -> Any:
    if world is None:
        return None
    parsed = parse_session_id(session_id)
    return None if parsed is None else world.row(parsed)


def _report_html(case: Case, document: dict[str, Any]) -> str:
    rows = "\n".join(
        "<tr><td>{id}</td><td>{stage}</td><td>{note}</td><td>{who}</td><td>{when}</td></tr>".format(
            id=html.escape(entry["session_id"]),
            stage=html.escape(str(entry.get("stage", ""))),
            note=html.escape(str(entry.get("note", ""))),
            who=html.escape(entry["pinned_by"]),
            when=html.escape(entry["pinned_at"]),
        )
        for entry in document["evidence"]
    )
    notes = "\n".join(
        f"<li><b>{html.escape(note['author_id'])}</b> "
        f"<i>{html.escape(note['created_at'])}</i><br>{html.escape(note['body'])}</li>"
        for note in document["notes"]
    )
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>{html.escape(case.title)}</title>
<style>body{{font:14px system-ui,sans-serif;margin:2rem;max-width:60rem}}
table{{border-collapse:collapse;width:100%}}td,th{{border:1px solid #ccc;padding:.35rem .5rem;
text-align:left}}th{{background:#f4f4f5}}</style></head><body>
<h1>{html.escape(case.title)}</h1>
<p><b>{html.escape(case.id)}</b> &middot; {html.escape(case.status)} &middot;
severity {html.escape(case.severity)} &middot; owner {html.escape(case.owner_id)}</p>
<p>{html.escape(case.summary or "")}</p>
<h2>Evidence ({len(document["evidence"])})</h2>
<table><tr><th>Session</th><th>Stage</th><th>Note</th><th>Pinned by</th><th>Pinned at</th></tr>
{rows}</table>
<h2>Notes ({len(document["notes"])})</h2>
<ul>{notes}</ul>
<p><small>Generated by the Capture API simulator at
{html.escape(document["generated_at"])}.</small></p>
</body></html>
"""


def build_archive(world: World | None, case: Case, generated_at: datetime) -> bytes:
    document = _evidence_document(world, case, generated_at)
    buffer = BytesIO()
    used: set[str] = set()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("evidence.json", json.dumps(document, indent=2, ensure_ascii=False))
        archive.writestr("report.html", _report_html(case, document))
        if world is None:
            return buffer.getvalue()
        for pin in case.evidence:
            row = _row(world, pin.session_id)
            if row is None:
                continue
            if world.pcap_available(row):
                archive.writestr(f"pcaps/{pin.session_id}.pcap", world.pcap(row))
            for carved in world.files_for_row(row):
                if carved.purged:
                    continue
                name = _unique(ascii_fallback_name(carved.name), used)
                archive.writestr(f"files/{name}", world.file_bytes(carved))
    return buffer.getvalue()


def _unique(name: str, used: set[str]) -> str:
    candidate = name or "file"
    suffix = 1
    while candidate in used:
        suffix += 1
        stem, dot, extension = name.rpartition(".")
        candidate = f"{stem}-{suffix}{dot}{extension}" if dot else f"{name}-{suffix}"
    used.add(candidate)
    return candidate


class ExportStore:
    def __init__(
        self,
        clock: CaptureClock,
        time_source: TimeSource,
        cases: CaseStore,
        world: Callable[[], World | None],
        seed: str,
    ) -> None:
        self._clock = clock
        self._time = time_source
        self._cases = cases
        self._world = world
        self._seed = seed
        self._exports: dict[str, ExportRecord] = {}
        self._counter = 0

    def _new_id(self) -> str:
        self._counter += 1
        digest = hashlib.blake2b(
            f"{self._seed}|export|{self._counter}".encode(), digest_size=6
        ).hexdigest()
        return f"exp_{digest}"

    def _expired(self, record: ExportRecord) -> bool:
        if record.ready_mono is None:
            return False
        return self._time.monotonic() - record.ready_mono > TTL_S

    def _percent(self, record: ExportRecord) -> float:
        if record.state == "ready":
            return 100.0
        elapsed = self._time.monotonic() - record.created_mono
        if elapsed <= QUEUED_S:
            return 0.0
        share = (elapsed - QUEUED_S) / max(0.001, DURATION_S - QUEUED_S)
        return round(min(99.0, share * 100.0), 1)

    def to_model(self, record: ExportRecord) -> Export:
        expires_at = (
            record.ready_at + timedelta(seconds=TTL_S) if record.ready_at is not None else None
        )
        return Export(
            id=record.id,
            case_id=record.case_id,
            state=record.state,
            percent=self._percent(record),
            expires_at=expires_at,
        )

    def create(self, case: Case) -> ExportRecord:
        record = ExportRecord(
            id=self._new_id(),
            case_id=case.id,
            created_mono=self._time.monotonic(),
            filename=archive_filename(case),
        )
        self._exports[record.id] = record
        return record

    def tick(self) -> None:
        now = self._time.monotonic()
        for record in self._exports.values():
            if record.state == "ready":
                if record.archive is not None and self._expired(record):
                    record.archive = None
                continue
            elapsed = now - record.created_mono
            if elapsed >= DURATION_S:
                self._finish(record)
            elif elapsed > QUEUED_S:
                record.state = "running"

    def _finish(self, record: ExportRecord) -> None:
        case = self._cases.get(record.case_id)
        generated_at = self._clock.now()
        record.archive = build_archive(self._world(), case, generated_at)
        record.state = "ready"
        record.ready_mono = self._time.monotonic()
        record.ready_at = generated_at

    def get(self, export_id: str) -> ExportRecord:
        self.tick()
        record = self._exports.get(export_id)
        if record is None:
            raise DomainError.not_found("export_not_found", f"No export '{export_id}'.")
        if self._expired(record):
            record.archive = None
            raise DomainError.not_found(
                "export_expired", "This export has expired; create a new one."
            )
        return record

    def archive(self, export_id: str) -> ExportRecord:
        record = self.get(export_id)
        if record.state != "ready" or record.archive is None:
            raise DomainError(
                409,
                "not_ready",
                "This export is not ready yet; poll GET /v1/exports/{id} until state is 'ready'.",
                extra={"state": record.state},
            )
        return record

    def stream(self, record: ExportRecord) -> Iterator[bytes]:
        data = record.archive or b""
        for start in range(0, len(data), CHUNK):
            yield data[start : start + CHUNK]

    def for_case(self, case_id: str) -> list[ExportRecord]:
        return [record for record in self._exports.values() if record.case_id == case_id]

    def reset(self) -> None:
        self._exports.clear()
        self._counter = 0

    def __len__(self) -> int:
        return len(self._exports)


def get_exports(conn: HTTPConnection) -> ExportStore:
    store = getattr(conn.app.state, "exports", None)
    if not isinstance(store, ExportStore):
        raise DomainError.unavailable("exports_unavailable", "The export store is not ready.", 5)
    return store


ExportsDep = Annotated[ExportStore, Depends(get_exports)]


@asynccontextmanager
async def lifespan(app: FastAPI) -> Any:

    def world() -> World | None:
        return cast(World | None, getattr(app.state, "world", None))

    store = ExportStore(
        app.state.clock, app.state.time, app.state.cases, world, app.state.settings.seed
    )
    app.state.exports = store

    async def poll() -> None:
        while True:
            await asyncio.sleep(0.25)
            store.tick()

    task = asyncio.create_task(poll())
    try:
        yield
    finally:
        task.cancel()
        with suppress(asyncio.CancelledError):
            await task
        store.reset()
